name: Theme

on: push

jobs:

  test:
    name: Test and Build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Node requirements
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer@1

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Start the Docker testing environment
        run: npm run env start

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
